#################################################################
## 3D Printer Automations
#################################################################

        ##########################################################
        ## Prusa MK4 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Print Finished
  id: '3d_printer_prusa_mk4_print_finished'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_mk4
      to: 'finished'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: 3D Print Complete
        data:
          tag: prusa_mk4_finished
          group: 3d_printer


        ##########################################################
        ## Prusa MK4 Print Error
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Print Error
  id: '3d_printer_prusa_mk4_print_error'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.prusa_mk4_nozzle_temperature
      below: 165
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: sensor.prusa_mk4
      state: 'printing'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: 3D Print Error
        data:
          tag: prusa_error
          group: 3d_printer


        ##########################################################
        ## Prusa MK4 Print Error Status
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Print Error Status
  id: '3d_printer_prusa_mk4_print_error_status'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_mk4
      to: 'error'
    - trigger: state
      entity_id: sensor.prusa_mk4
      to: 'attention'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: 3D Print Error
        data:
          tag: prusa_error
          group: 3d_printer