#################################################################
## Alarm System - Notifications and Automations
#################################################################

        ##########################################################
        ## Alarm Trouble Notification
        ##########################################################

- alias: Alarm - Trouble Notification
  id: 'alarm_trouble_notification'  

  triggers:
    - trigger: state
      entity_id: sensor.alarm_system_trouble
      from: "false"
      to: "true"

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Alarm System Trouble Light On"


        ##########################################################
        ## Away Notification - Garage Opened
        ##########################################################

- alias: Away Notification - Garage Door Opened
  id: 'away_notification_garage_door_opened'

  triggers:
    - trigger: state
      entity_id: group.garage_doors
      from: 'off'
      to: 'on'

  conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: state
      entity_id: input_boolean.disable_away_notifications
      state: 'off'

  actions:
    - delay: '00:00:10'
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Away Alert - Garage Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.garage_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Away Alert - Garage Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.garage_high

        ##########################################################
        ## Away Notification - Back Door Opened
        ##########################################################

- alias: Away Notification - Back Door Opened
  id: 'away_notification_back_door_opened'

  triggers:
    - trigger: state
      entity_id: binary_sensor.back_door
      from: 'off'
      to: 'on'

  conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: state
      entity_id: input_boolean.disable_away_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Away Alert - Back Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.south_back_door_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Away Alert - Back Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.south_back_door_high

        ##########################################################
        ## Away Notification - Front Door Opened
        ##########################################################

- alias: Away Notification - Front Door Opened
  id: 'away_notification_front_door_opened'


  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'

  conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: state
      entity_id: input_boolean.disable_away_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Away Alert - Front Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.north_front_door_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Away Alert - Front Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.north_front_door_high

        ##########################################################
        ## Away Notification - Basement Door Opened
        ##########################################################

- alias: Away Notification - Basement Door Opened
  id: 'away_notification_basement_door_opened'

  triggers:
    - trigger: state
      entity_id: binary_sensor.basement_door
      from: 'off'
      to: 'on'

  conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: state
      entity_id: input_boolean.disable_away_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Away Alert - Basement Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.west_walkout_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Away Alert - Basement Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.west_walkout_high

        ##########################################################
        ## Away Notification - Garage Back Door Opened
        ##########################################################

- alias: Away Notification - Garage Back Door Opened
  id: 'away_notification_garage_back)door_opened'

  triggers:
    - trigger: state
      entity_id: binary_sensor.garage_back_door
      from: 'off'
      to: 'on'

  conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: state
      entity_id: input_boolean.disable_away_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Away Alert - Garage Back Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.garage_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Away Alert - Garage Back Door Opened"
        data:
          push:
            category: camera
          entity_id: camera.garage_high

        #################################################################
        ## Notification - Exterior Door Open Long
        #################################################################

- alias: Notification - Exterior Door Open Long
  id: 'alarm_exterior_door_open_long'

  triggers:
    - trigger: state
      entity_id: binary_sensor.back_door
      from: "off"
      to: "on"
      for:
        hours: 0
        minutes: 1
        seconds: 0        
      variables:
        trigger_message: "Alert - Back Door Opened 1 Minute"
        trigger_camera: "camera.south_back_door_high"
    - trigger: state
      entity_id: binary_sensor.basement_door
      from: "off"
      to: "on"
      for:
        hours: 0
        minutes: 1
        seconds: 0        
      variables:
        trigger_message: "Alert - Basement Door Opened 1 Minute"
        trigger_camera: "camera.west_walkout_high"
    - trigger: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
      for:
        hours: 0
        minutes: 1
        seconds: 0        
      variables:
        trigger_message: "Alert - Front Door Opened 1 Minute"
        trigger_camera: "camera.north_front_door_high"        
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "{{ trigger_message }}"
        data:
          push:
            category: camera
          entity_id: "{{ trigger_camera }}"
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "{{ trigger_message }}"
        data:
          push:
            category: camera
          entity_id: "{{ trigger_camera }}"

        #################################################################
        ## Notification - Garage Entry Door Open Long
        #################################################################

- alias: Notification - Garage Entry Door Open Long
  id: 'alarm_garage_entry_door_open_long'

  triggers:
    - trigger: state
      entity_id: binary_sensor.garage_entry_door
      from: "off"
      to: "on"
      for:
        hours: 0
        minutes: 1
        seconds: 0        
      variables:
        trigger_message: "Alert - Garage Entry Door Opened 1 Minute"
        trigger_camera: "camera.garage_high"
  conditions:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.double_garage
        state: "open"
      - condition: state
        entity_id: cover.single_garage
        state: "open" 
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "{{ trigger_message }}"
        data:
          push:
            category: camera
          entity_id: "{{ trigger_camera }}"
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "{{ trigger_message }}"
        data:
          push:
            category: camera
          entity_id: "{{ trigger_camera }}"
