#################################################################
## Aquarium - Notifications and Automations
#################################################################

        ##########################################################
        ## Red Sea UV Light - Total Counter
        ##########################################################

- alias: Red Sea UV Light Usage - Total Counter
  id: 'red_sea_uv_usage_total_counter'

  trigger:
    - platform: time
      at: '23:59:00'

  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.redsea_uv_light_usage
        value: "{{ states.sensor.red_sea_aqua_uv_runtime_today.state | float / 24 + states.input_number.redsea_uv_light_usage.state | float }}" 

        ##########################################################
        ## Red Sea Dosing - Enabled
        ##########################################################

- alias: Red Sea Dosing - Enabled
  id: 'red_sea_dosing_enabled'

  trigger:
    - platform: state
      entity_id: input_boolean.red_sea_dosing
      to: 'on'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.redsea_uv_sterlizer

        ##########################################################
        ## Red Sea Dosing - Disabled
        ##########################################################

- alias: Red Sea Dosing - Disabled
  id: 'red_sea_dosing_disabled'

  trigger:
    - platform: state
      entity_id: input_boolean.red_sea_dosing
      to: 'on'
      for:
        hours: "{{ states.input_number.red_sea_dosing_delay.state | int }}"
        minutes: 0
        seconds: 0      

  action:
    - service: homeassistant.turn_on
      entity_id: switch.redsea_uv_sterlizer
    - service: homeassistant.turn_off
      entity_id: input_boolean.red_sea_dosing     


        ##########################################################
        ## Red Sea Algae Scrubber Light On
        ##########################################################

- alias: Red Sea Algae Scrubber Light On
  id: 'red_sea_algae_scrubber_light_on'

  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.red_sea_algae_scrubber_light_on_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
        
  action:
    - service: homeassistant.turn_on
      entity_id: switch.red_sea_algae_scrubber_light


        ##########################################################
        ## Red Sea Algae Scrubber Light Off
        ##########################################################

- alias: Red Sea Algae Scrubber Light Off
  id: 'red_sea_algae_scrubber_light_off'

  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.red_sea_algae_scrubber_light_off_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
        
  action:
    - service: homeassistant.turn_off
      entity_id: switch.red_sea_algae_scrubber_light

        ##########################################################
        ## Red Sea Algae Scrubber Light Not Running
        ##########################################################

- alias: Red Sea Algae Scrubber Light Not Running
  id: 'red_sea_algae_scrubber_light_not_running'

  trigger:
    - platform: numeric_state
      entity_id: sensor.red_sea_algae_scrubber_light_current_consumption
      below: 13
      for:
        hours: 0
        minutes: 5
        seconds: 0
  condition:
    - condition: state
      entity_id: switch.red_sea_algae_scrubber_light
      state: 'on'
  
  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Red Sea Algae Scrubber Light Not Running"

        ##########################################################
        ## Red Sea Algae Scrubber Pump Not Running
        ##########################################################

        ##########################################################
        ## Biocube32 High Temperature Alert
        ##########################################################

- alias: Red Sea High Temperature
  id: 'redsea_temperature_high'

  trigger:
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_1
      above: 79
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_2
      above: 79
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_3
      above: 79
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_4
      above: 79
      for:
        hours: 0
        minutes: 20
        seconds: 0
  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Red Sea Temp High - Check Tank!!"
    - service: notify.mobile_app_USER2_iphone
      data:
        message: "Red Sea Temp High - Check Tank!!"


        ##########################################################
        ## Red Sea Low Temperature Alert
        ##########################################################

- alias: Red Sea Low Temperature
  id: 'redsea_temperature_low'

  trigger:
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_1
      below: 76
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_2
      below: 76
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_3
      below: 76
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - platform: numeric_state
      entity_id: sensor.red_sea_temperature_4
      below: 76
      for:
        hours: 0
        minutes: 10
        seconds: 0
  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: "Biocube Temp Low - Check Tank Temp!!"
    - service: notify.mobile_app_USER2_iphone
      data:
        message: "Biocube Temp Low - Check Tank Temp!!"