#################################################################
## Aquarium - Notifications and Automations
#################################################################

        ##########################################################
        ## Red Sea UV Light - Total Counter
        ##########################################################

- alias: Red Sea UV Light Usage - Total Counter
  id: 'red_sea_uv_usage_total_counter'

  triggers:
    - trigger: time
      at: '23:59:00'

  actions:
    - action: input_number.set_value
      data_template:
        entity_id: input_number.redsea_uv_light_usage
        ## NEED TO FIX
        value: "{{ states.sensor.red_sea_aqua_uv_runtime_today.state | float / 24 + states.input_number.redsea_uv_light_usage.state | float }}" 

        ##########################################################
        ## Red Sea Dosing - Enabled
        ##########################################################

- alias: Red Sea Dosing - Enabled
  id: 'red_sea_dosing_enabled'

  triggers:
    - trigger: state
      entity_id: input_boolean.red_sea_dosing
      to: 'on'

  actions:
    - action: homeassistant.turn_off
      entity_id: switch.1_uv_light

        ##########################################################
        ## Red Sea Dosing - Disabled
        ##########################################################

- alias: Red Sea Dosing - Disabled
  id: 'red_sea_dosing_disabled'

  triggers:
    - trigger: state
      entity_id: input_boolean.red_sea_dosing
      to: 'on'
      for:
        hours: "{{ states.input_number.red_sea_dosing_delay.state | int }}"
        minutes: 0
        seconds: 0      

  actions:
    - action: homeassistant.turn_on
      entity_id: switch.1_uv_light
    - action: homeassistant.turn_off
      entity_id: input_boolean.red_sea_dosing     


        ##########################################################
        ## Red Sea Algae Scrubber Pump Failure
        ##########################################################

#- alias: Red Sea Algae Scrubber Pump Failure
#  id: 'red_sea_algae_scrubber_pump_failure'

#  triggers:
#    - trigger: numeric_state
#      entity_id: sensor.1_algae_scrubber_pump_current_consumption
#      below: 15
#      for:
#        hours: 0
#        minutes: 5
#        seconds: 0
#  conditions:
#    - condition: state
#      entity_id: switch.1_algae_scrubber_pump
#      state: 'on'
  
#  actions:
#    - action: notify.mobile_app_USER1_iphone
#      data:
#        message: "Red Sea Algae Scrubber Pump Possible Failure. Low Power Usage"

        ##########################################################
        ## Red Sea Algae Scrubber Pump Not Running
        ##########################################################

#- alias: Red Sea Algae Scrubber Pump Not Running
#  id: 'red_sea_algae_scrubber_pump_not_running'

#  triggers:
#    - trigger: state
#      entity_id: switch.1_algae_scrubber_pump
#      to: 'off'  
#      for:
#        hours: 0
#        minutes: 20
#        seconds: 0
#  actions:
#    - action: notify.mobile_app_USER1_iphone
#      data:
#        message: "Red Sea Algae Scrubber Pump Not Running. Check Pump"


        ##########################################################
        ## Red Sea High Temperature Alert
        ##########################################################

- alias: Red Sea High Temperature
  id: 'redsea_temperature_high'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_1
      above: input_number.red_sea_high_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_2
      above: input_number.red_sea_high_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_3
      above: input_number.red_sea_high_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_4
      above: input_number.red_sea_high_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Red Sea Temp High - Check Tank!!"
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Red Sea Temp High - Check Tank!!"


        ##########################################################
        ## Red Sea Low Temperature Alert
        ##########################################################

- alias: Red Sea Low Temperature
  id: 'redsea_temperature_low'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_1
      below: input_number.red_sea_low_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_2
      below: input_number.red_sea_low_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_3
      below: input_number.red_sea_low_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
    - trigger: numeric_state
      entity_id: sensor.red_sea_temperature_4
      below: input_number.red_sea_low_temp_alarm
      for:
        hours: 0
        minutes: 20
        seconds: 0
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Red Sea Temp Low - Check Tank Temp!!"
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Red Sea Temp Low - Check Tank Temp!!"

        ##########################################################
        ## Red Sea Protein Skimmer Off with Return Pump
        ##########################################################

- alias: Red Sea Protein Skimmer Pump Off with Return Pump
  id: 'red_sea_protein_skimmer_pump_off_with_return_pump'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.1_return_pump_current_consumption
      below: 30
#      for:
#        hours: 0
#        minutes: 0
#        seconds: 2
  conditions:
    - condition: state
      entity_id: switch.1_protein_skimmer_pump
      state: 'on'
  
  actions:
    - action: homeassistant.turn_off
      entity_id: switch.1_protein_skimmer_pump     
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Red Sea Protein Skimmer Pump Turned Off with Return Pump"


        ##########################################################
        ## Red Sea Protein Skimmer Full
        ##########################################################

- alias: Red Sea Protein Skimmer Full
  id: 'red_sea_protein_skimmer_full'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.1_protein_skimmer_current_consumption
      below: 10
      for:
        hours: 0
        minutes: 5
        seconds: 0
  conditions:
    - condition: state
      entity_id: switch.1_protein_skimmer_pump
      state: 'on'
  
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Red Sea Protein Skimmer possibly FULL! Low Power Usage."
        