#################################################################
## Audio Notifications
#################################################################

        ##########################################################
        ## Audio Notification for Water Detected Kitchen Sink
        ##########################################################
- alias: Audio Notification - Kitchen Sink Water Sensor

  triggers:
    - trigger: event
      event_type: timer.started
      event_data:
        entity_id: timer.alarm_kitchen_sink_water_sensor
  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  actions:
    - action: media_player.volume_set
      entity_id:
        - media_player.office
      data:
        volume_level: '0.6'
    - action: tts.google_translate_say
      entity_id: media_player.office
      data:
        message: 'Warning, Warning. Water detected by the Kitchen Sink.'

        ##########################################################
        ## Audio Notification Loop for Water Detected Kitchen Sink
        ##########################################################
- alias: Audio Notification Loop - Kitchen Sink Water Sensor
  triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.alarm_kitchen_sink_water_sensor
  conditions:
    condition: state
    entity_id: binary_sensor.kitchen_sink_water_sensor
    state: 'on'
  actions:
  - action: timer.start
    entity_id: timer.alarm_kitchen_sink_water_sensor
