#################################################################
## Bedtime Automations
#################################################################

        ##########################################################
        ## Bedtime - Master Bedroom
        ##########################################################

- alias: Bedtime Master Bedroom
  id: 'bedtime_master_bedroom'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5

  actions:
    - action: light.turn_off
      entity_id:
        - light.master_bedroom
    - action: switch.turn_on
      entity_id:
        - switch.sound_machine

        ##########################################################
        ## Reset Bedtime Switch
        ##########################################################

- alias: Bedtime - Reset Switch
  id: 'bedtime_reset_switch'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  actions:
    - action: homeassistant.turn_off
      entity_id: input_boolean.bedtime
