        ##########################################################
        ## Turn On Front Door when Door Bell Rings
        ##########################################################

- alias: Doorbell - Turn On Front Door when Rung
  id: 'doorbell_turn_on_front_door_when_rung'    

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_doorbell
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness_pct: 100
        kelvin: 2700

        ##########################################################
        ## Reset Front Door Brightness After Doorbell Rings
        ##########################################################

- alias: Doorbell - Reset Front Door After Ring
  id: 'doorbell_reset_front_after_ring' 

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_doorbell
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: scene.turn_on
      data_template:
        entity_id: scene.front_{{ states.input_select.outdoor_theme.state | lower | replace(' ', '_') | replace('\'', '') }}

        ##########################################################
        ## Turn On Front Door when Person Detected
        ##########################################################

- alias: Doorbell - Turn On Front Door when Person Detected
  id: 'doorbell_turn_on_front_door_when_person_detected' 

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_person_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness_pct: 100
        kelvin: 2700

        ##########################################################
        ## Reset Front Door After Person Detected - Before Off
        ##########################################################

- alias: Doorbell - Reset Front Door After Person Detected before 11:30
  id: 'doorbell_reset_front_door_after_person_detected_before_11' 
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_person_detected
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: time
      before: '23:30:00'       
    - condition: time
      after: '16:00:00'      

  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness_pct: 30
        kelvin: 2700
        ##########################################################
        ## Reset Front Door After Person Detected - After Off
        ##########################################################

- alias: Doorbell - Reset Front Door After Person Detected after 11:30
  id: 'doorbell_reset_front_door_after_person_detected_after_11' 
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_person_detected
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0
      
  condition:
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: or
      conditions:      
        - condition: time
          before: '08:00:00'
        - condition: time  
          after: '23:30:00' 
  action:
    - service: light.turn_off
      entity_id: light.front_door
              
        ##########################################################
        ## Door Bell Rings - Audio Notification 
        ##########################################################

- alias: Doorbell - Play Sound When Someone Rings Doorbell
  id: 'doorbell_play_sound_when_someone_rings_doorbell' 
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_doorbell
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.office
      data:
        volume_level: '0.6'
    - delay: '00:00:01'
    - service: tts.amazon_polly_say
      entity_id: media_player.office
      data:
        message: 'Someone is at the Front Door.'