#################################################################
## Garage Automations
#################################################################

        ##########################################################
        ## Double Garage Door Open 15 Minutes at Night - Notification
        ##########################################################

- alias: Notification - Double Garage Door Open 15 Minutes At Night
  id: 'double_garage_open_15_minutes_at_night_notification'

  triggers:
    - trigger: state
      entity_id: cover.double_garage
      to: 'open'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
      before: sunrise

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Double Garage Door Still Open"
        data:
          push:
            category: camera
          entity_id: camera.garage_high

        ##########################################################
        ## Single Garage Door Open 15 Minutes At Night - Notification
        ##########################################################

- alias: Notification - Single Garage Door Open 15 Minutes At Night
  id: 'single_garage_open_15_minutes_at_night_notification'

  triggers:
    - trigger: state
      entity_id: cover.single_garage
      to: 'open'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
      before: sunrise

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Single Garage Door Still Open"
        data:
          push:
            category: camera
          entity_id: camera.garage_high



        ##########################################################
        ## Double Garage Door Left Open For 20 Minutes Cold Weather - Notification
        ##########################################################

- alias: Notification - Double Garage Door Left Open 20m When Cold
  id: 'double_garage_open_20_minutes_when_cold_notification'

  triggers:
    - trigger: state
      entity_id: cover.double_garage
      to: 'open'
      for:
        hours: 0
        minutes: 20
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.pirateweather_temperature
      below: 45

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Double Garage Door Open 20m in Cold Weather"
        data:
          push:
            category: camera
          entity_id: camera.garage_high

        ##########################################################
        ## Single Garage Door Left Open For 20 Minutes Cold Weather - Notification
        ##########################################################

- alias: Notification - Single Garage Door Left Open 20m When Cold
  id: 'single_garage_open_20_minutes_when_cold_notification'

  triggers:
    - trigger: state
      entity_id: cover.single_garage
      to: 'open'
      for:
        hours: 0
        minutes: 20
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.pirateweather_temperature
      below: 45

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Single Garage Door Open 20m in Cold Weather"
        data:
          push:
            category: camera
          entity_id: camera.garage_high


        ##########################################################
        ## Double Garage Door Left Open At Night - Notification
        ##########################################################

- alias: Notification - Double Garage Door Left Open At Night
  id: 'double_garage_left_open_at_night_notification'

  triggers:
    - trigger: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: cover.double_garage
      state: 'open'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Double Garage Door Still Open"
        data:
          push:
            category: camera
          entity_id: camera.garage_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Double Garage Door Still Open"
        data:
          push:
            category: camera
          entity_id: camera.garage_high

        ##########################################################
        ## Single Garage Door Left Open At Night - Notification
        ##########################################################

- alias: Notification - Single Garage Door Left Open At Night
  id: 'single_garage_left_open_at_night_notification'

  triggers:
    - trigger: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: cover.single_garage
      state: 'open'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Single Garage Door Still Open"
        data:
          push:
            category: camera
          entity_id: camera.garage_high
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Single Garage Door Still Open"
        data:
          push:
            category: camera
          entity_id: camera.garage_high

        ##########################################################
        ## Double Garage Opening
        ##########################################################

- alias: Double Garage Door Opening
  id: 'double_garage_door_opening'

  triggers:
    - trigger: state
      entity_id: input_boolean.garage_double_door_motor
      to: 'on'

  actions:
    - delay: '00:00:45'
    - action: homeassistant.turn_off
      entity_id: input_boolean.garage_double_door_motor

        ##########################################################
        ## USER1 Home from Driving Open Garage Door
        ##########################################################

- alias: Garage - USER1 Home from Driving Open Garage Door
  id: 'garage_USER1_home_from_driving_open_garage_door'

  triggers:
    - trigger: state
      entity_id: person.USER1
      from: 'not_home'
      to: 'home'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: sensor.USER1_iphone_activity
      state: 'Automotive'
    - condition: state
      entity_id: cover.double_garage
      state: 'closed'
    - condition: state
      entity_id: input_boolean.garage_double_door_motor
      state: 'off'

  actions:
    - action: homeassistant.turn_on
      entity_id: input_boolean.garage_double_door_motor    
    - action: cover.open_cover
      entity_id: cover.double_garage

        ##########################################################
        ## USER1 Away from Driving Close Garage Door
        ##########################################################

- alias: Garage - USER1 Away from Driving Close Garage Door
  id: 'garage_USER1_away_from_driving_close_garage_door'

  triggers:
    - trigger: state
      entity_id: person.USER1
      from: 'home'
      to: 'not_home'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: sensor.USER1_iphone_activity
      state: 'Automotive'
    - condition: state
      entity_id: cover.double_garage
      state: 'open'
    - condition: state
      entity_id: input_boolean.garage_double_door_motor
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: Garage Left Open!
        data:
          apns_headers:
           'apns-collapse-id': 'doublegarage-close'
          push:
            badge: 0
            category: "doublegarageclose"

        ##########################################################
        ## USER2 Home from Driving Open Garage Door
        ##########################################################

- alias: Garage - USER2 Home from Driving Open Garage Door
  id: 'garage_USER2_home_from_driving_open_garage_door'

  triggers:
    - trigger: state
      entity_id: person.USER2
      from: 'not_home'
      to: 'home'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: sensor.USER2_iphone_activity
      state: 'Automotive'
    - condition: state
      entity_id: cover.double_garage
      state: 'closed'
    - condition: state
      entity_id: input_boolean.garage_double_door_motor
      state: 'off'

  actions:
    - action: homeassistant.turn_on
      entity_id: input_boolean.garage_double_door_motor  
    - action: cover.open_cover
      entity_id: cover.double_garage

        ##########################################################
        ## USER2 Away from Driving Close Garage Door
        ##########################################################

- alias: Garage - USER2 Away from Driving Close Garage Door
  id: 'garage_USER2_away_from_driving_close_garage_door'

  triggers:
    - trigger: state
      entity_id: person.USER2
      from: 'home'
      to: 'not_home'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    - condition: state
      entity_id: sensor.USER2_iphone_activity
      state: 'Automotive'
    - condition: state
      entity_id: cover.double_garage
      state: 'open'
    - condition: state
      entity_id: input_boolean.garage_double_door_motor
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: Garage Left Open!
        data:
          apns_headers:
           'apns-collapse-id': 'doublegarage-close'
          push:
            badge: 0
            category: "doublegarageclose"            

        ##########################################################
        ## USER4 Away from Driving Close Garage Door
        ##########################################################

- alias: Garage - USER4 Away from Driving Close Garage Door
  id: 'garage_USER4_away_from_driving_close_garage_door'

  triggers:
    - trigger: state
      entity_id: person.USER4
      from: 'home'
      to: 'not_home'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_auto_garage
      state: 'off'
    #- condition: state
    #  entity_id: sensor.USER4_iphone_activity
    #  state: 'Automotive'
    - condition: state
      entity_id: cover.double_garage
      state: 'open'
    - condition: state
      entity_id: input_boolean.garage_double_door_motor
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: USER4 Left Garage Open!
        data:
          apns_headers:
           'apns-collapse-id': 'doublegarage-close'
          push:
            badge: 0
            category: "doublegarageclose"

        ##########################################################
        ## Home Away Double Garage Left Open
        ##########################################################

- alias: Garage - Home Away Double Garage Left Open
  id: 'garage_home_away_double_garage_left_open'

  triggers:
    - trigger: numeric_state
      entity_id: zone.home
      below: 1

  conditions:
    - condition: state
      entity_id: cover.double_garage
      state: 'open'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: AWAY ALERT - Double Garage Left Garage Open!
        data:
          apns_headers:
           'apns-collapse-id': 'doublegarage-close'
          push:
            badge: 0
            category: "doublegarageclose"

        ##########################################################
        ## Home Away Single Garage Left Open
        ##########################################################

- alias: Garage - Home Away Single Garage Left Open
  id: 'garage_home_away_single_garage_left_open'

  triggers:
    - trigger: numeric_state
      entity_id: zone.home
      below: 1

  conditions:
    - condition: state
      entity_id: cover.single_garage
      state: 'open'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: AWAY ALERT - Single Garage Left Garage Open!
        data:
          apns_headers:
           'apns-collapse-id': 'singlegarage-close'
          push:
            badge: 0
            category: "singlegarageclose"

        ##########################################################
        ## Double Garage Door Counter
        ##########################################################

- alias: Double Garage Door Counter
  id: 'garage_double_garage_counter'

  triggers:
    - trigger: state
      entity_id: cover.double_garage
      to: 
      - 'open'
      - 'closed'
      
  action:  
    - action: counter.increment
      entity_id: counter.double_garage_spring_counter


        ##########################################################
        ## Single Garage Door Counter
        ##########################################################

- alias: Single Garage Door Counter
  id: 'garage_single_garage_counter'
  
  triggers:
    - trigger: state
      entity_id: cover.single_garage
      to: 
      
  action:  
    - action: counter.increment
      entity_id: counter.single_garage_spring_counter