#################################################################
## Hardware Automation and Notifications
#################################################################

        #################################################################
        ## Home Assistant Startup Success
        #################################################################

- alias: Notification Text - Home Assistant Start

  triggers:
    - trigger: homeassistant
      event: start

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Home Assistant Started"

        #################################################################
        ## Home Assistant Started Notification
        #################################################################

- alias: Notification Log - Home Assistant Start

  triggers:
    - trigger: homeassistant
      event: start
  actions:
    action: system_log.write
    data:
      message: "Home Assistant started."

#################################################################
## NAS Warning
#################################################################

- alias: Notification Text - NAS Warning

  triggers:
    - trigger: state
      entity_id: sensor.nas_status
      to: 'warning'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "NAS RAID Failing"

#################################################################
## UPS Alerts
#################################################################


        ##########################################################
        ## UPS Power Loss Alert
        ##########################################################

- alias: Notification Text - UPS Power Loss Alert

  triggers:
    - trigger: state
      entity_id: sensor.ups_status
      from: "Online"
      to: "On Battery Battery Discharging"

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Power Outage - UPS Runtime - {{states.sensor.ups_battery_runtime_mins.state}}"

        ##########################################################
        ## UPS Low Runtime Alert
        ##########################################################

- alias: Notification Text - UPS Low Runtime Alert

  triggers:
    - trigger: numeric_state
      entity_id: sensor.ups_battery_runtime_mins
      below: 15

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "15 mins of UPS Battery Remaining!"


        #################################################################
        ## Monitor ZWave Unavailable
        #################################################################

- alias: Zwave - Unavailble Sensors in Home Assistant
  id: 'hardware_zwave_unavailable_sesnors'

  triggers:
    - trigger: state
      entity_id: binary_sensor.basement_drain_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Basement Drain Water Sensor Unavailable"
    - trigger: state
      entity_id: binary_sensor.washing_machine_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Washing Machine Water Sensor Unavailable"
    - trigger: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Kitchen Sink Water Sensor Unavailable"     
    - trigger: state
      entity_id: binary_sensor.refrigerator_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Refrigerator Water Sensor Unavailable" 
    - trigger: state
      entity_id: binary_sensor.filtration_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Filtration Water Sensor Unavailable"     
    - trigger: state
      entity_id: binary_sensor.red_sea_floor_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Red Sea Floor Water Sensor Unavailable"       
    - trigger: state
      entity_id: binary_sensor.red_sea_sump_water_sensor
      to: "unavailable"
      variables:
        trigger_message: "Red Sea Sump Water Sensor Unavailable"
    - trigger: state
      entity_id:  switch.basement_bathroom 
      to: "unavailable"
      variables:
        trigger_message: "Basement Bathroom Switch Unavailable"
    - trigger: state
      entity_id:  switch.basement_room
      to: "unavailable"
      variables:
        trigger_message: "Basement Room Switch Unavailable"
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "{{ trigger_message }}"
