#################################################################
## Inside Lighting Automation
#################################################################

        ##########################################################
        ## Household Home Turn on Lights
        ##########################################################

- alias: Household Home

  triggers:
    - trigger: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  actions:
    action: light.turn_on
    entity_id: light.family_room
    data:
     brightness: 255

        ##########################################################
        ## Pantry Light On When Door Open
        ##########################################################

- alias: Pantry Light On

  triggers:
    - trigger: state
      entity_id: binary_sensor.pantry_door
      from: 'off'
      to: 'on'

  actions:
    action: light.turn_on
    entity_id: light.pantry
    data:
     brightness: 255

        ##########################################################
        ## Pantry Light Off When Door Open
        ##########################################################

- alias: Pantry Light Off

  triggers:
    - trigger: state
      entity_id: binary_sensor.pantry_door
      from: 'on'
      to: 'off'

  actions:
    action: light.turn_off
    entity_id: light.pantry

        ##########################################################
        ## Hall Closet Lights On When Door Open
        ##########################################################

- alias: Hall Closet Light On

  triggers:
    - trigger: state
      entity_id: binary_sensor.hall_closet_door
      from: 'off'
      to: 'on'

  actions:
    action: light.turn_on
    entity_id: light.hall_closet
    data:
     brightness: 255

        ##########################################################
        ## Hall Closet Lights Off When Door Open
        ##########################################################

- alias: Hall Closet Lights Off

  triggers:
    - trigger: state
      entity_id: binary_sensor.hall_closet_door
      from: 'on'
      to: 'off'

  actions:
    action: light.turn_off
    entity_id: light.hall_closet

        ##########################################################
        ## Hall Closet Lights Off When On for 10 Minutes
        ##########################################################

- alias: Hall Closet Lights Off - Left Open

  triggers:
    - trigger: state
      entity_id: light.hall_closet
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: Hall Closet Lights Left On!
        data:
          apns_headers:
           'apns-collapse-id': 'hallcloset-lights'
          push:
            badge: 0
            category: "hallclosetlights"


        ##########################################################
        ## Turn off USER4 Bedroom Night Lights at 11:00pm
        ##########################################################

- alias: USER4 Bedroom Lights Off

  triggers:
    - trigger: time
      at: '23:00:00'

  conditions:
    - condition: state
      entity_id: person.USER4
      state: 'home'

  actions:
    - action: light.turn_off
      entity_id: light.USER4_bedroom


        ##########################################################
        ## Turn off USER3 Bedroom Night Lights at 11:00pm
        ##########################################################

- alias: USER3 Bedroom Lights Off

  triggers:
    - trigger: time
      at: '23:00:00'

  conditions:
    - condition: state
      entity_id: person.USER3
      state: 'home'

  actions:
    - action: light.turn_off
      entity_id: light.USER3_bedroom


        ##########################################################
        ## Turn off USER4 Bedroom When Away
        ##########################################################

- alias: USER4 Bedroom Lights Off - Away

  triggers:
    - trigger: state
      entity_id: person.USER4
      from: 'home'
      to: 'not_home'

  conditions:
    - condition: state
      entity_id: light.USER4_bedroom
      state: 'on'

  actions:
    - action: light.turn_off
      entity_id: light.USER4_bedroom


        ##########################################################
        ## Turn off USER3 Bedroom When Away
        ##########################################################

- alias: USER3 Bedroom Lights Off - Away

  triggers:
    - trigger: state
      entity_id: person.USER3
      from: 'home'
      to: 'not_home'

  conditions:
    - condition: state
      entity_id: light.USER3_bedroom
      state: 'on'

  actions:
    - action: light.turn_off
      entity_id: light.USER3_bedroom


        ##########################################################
        ## Turn off Basement Theme
        ##########################################################
- id: basement.light.off.reset_theme
  alias: Basement Lights Off - Reset Theme

  triggers:
    - trigger: state
      entity_id: light.basement
      from: 'on'
      to: 'off'

  actions:
    - action: input_select.select_option
      target:
        entity_id: input_select.basement_theme
      data:
        option: "None"      


        ##########################################################
        ## Wax Melt - Off after 5 Hours
        ##########################################################

- alias: Wax Melt - Off after Time
  id: 'wax_melt_off_after_time'

  triggers:
    - trigger: state
      entity_id: switch.wax_melt
      to: 'on'
      for:
        hours: 5
        minutes: 0
        seconds: 0

  actions:
    - action: homeassistant.turn_off
      entity_id: switch.wax_melt

        ##########################################################
        ## Wax Melt - Off after Away
        ##########################################################

- alias: Wax Melt - Off after Away
  id: 'wax_melt_off_after_away'

  triggers:
    - trigger: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'

  actions:
    - action: homeassistant.turn_off
      entity_id: switch.wax_melt