#################################################################
## Laundry Room Automations
#################################################################

        ##########################################################
        ## Washing Machine Done - Notification
        ##########################################################

- alias: Notification - Washing Machine Done

  triggers:
    - trigger: state
      entity_id: sensor.washing_machine_status
      from: 'running'
      to: 'not running'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Washing Machine - Done"

        ##########################################################
        ## Washing Machine Switch Off Notification
        ##########################################################

- alias: Laundry - Washing Machine Switch Off Notification

  triggers:
    - trigger: state
      entity_id: switch.washing_machine
      from: 'on'
      to: 'off'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: Washing Machine Switch Turned Off!
        data:
          apns_headers:
           'apns-collapse-id': 'laundry-switch'
          push:
            badge: 0
            category: "washingmachineswitch"
