#################################################################
## Magic Mirror Automations
#################################################################

        ##########################################################
        ## Magic Mirror Off when Away
        ##########################################################

- alias: Magic Mirror Off when Away
  id: 'magicmirror_off_away'

  triggers:
    - trigger: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'

  actions:
    - action: homeassistant.turn_off
      entity_id: switch.magicmirror_display


        ##########################################################
        ## Magic Mirror On when Home
        ##########################################################

- alias: Magic Mirror On when Home
  id: 'magicmirror_on_away'

  triggers:
    - trigger: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'

  conditions:
    - condition: time
      after: '05:00:00'
      before: '23:00:00'

  actions:
    - action: homeassistant.turn_on
      entity_id: switch.magicmirror_display
    - action: homeassistant.turn_on
      entity_id: switch.magicmirror_restart         

        ##########################################################
        ## Magic Mirror Turn off at Night
        ##########################################################

- alias: Magic Mirror Turn Off At Night
  id: 'magicmirror_turn_off_at_night'

  triggers:
    - trigger: time
      at: '23:00:00'

  actions:
    - action: homeassistant.turn_off
      entity_id: switch.magicmirror_display

        ##########################################################
        ## Magic Mirror Turn on at Morning
        ##########################################################

- alias: Magic Mirror Turn On At Morning
  id: 'magicmirror_turn_on_at_morning'

  triggers:
    - trigger: time
      at: '06:30:00'

  actions:
    - action: homeassistant.turn_on
      entity_id: switch.magicmirror_display
    - action: homeassistant.turn_on
      entity_id: switch.magicmirror_restart      