#################################################################
## Outside Lighting Automation
#################################################################

        ##########################################################
        ## Turn off Front and Walkout Lights at 11:30pm
        ##########################################################

- alias: Outside Lights - Front and Walkout Lights Off
  id: 'outside_lights_front_and_walkout_lights_off' 

  triggers:
    - trigger: time
      at: '23:30:00'

  actions:
    - action: homeassistant.turn_off
      entity_id: light.walkout
    - action: homeassistant.turn_off
      entity_id: light.front_door

        ##########################################################
        ## Dim Landscape and Garage Lights at 11:35pm
        ##########################################################

- alias: Outside Lights - Landscape Lights Dim
  id: 'outside_lights_landscape_lights_dim' 
  triggers:
    - trigger: time
      at: '23:35:00'

  actions:
    - action: light.turn_on
      entity_id: light.landscape
      data:
        transition: 5
        brightness_pct: 30
    - action: light.turn_on
      entity_id: light.garage
      data:
        transition: 5
        brightness_pct: 50

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:00am
        ##########################################################

- alias: Outside Lights - Off
  id: 'outside_lights_off' 
  triggers:
    - trigger: time
      at: '04:00:00'

  actions:
    - action: homeassistant.turn_off
      entity_id: light.garage
    - action: homeassistant.turn_off
      entity_id: light.landscape
    - action: homeassistant.turn_off
      entity_id: input_boolean.animate_outside

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:10am
        ##########################################################

- alias: Outside Lights - Off 2
  id: 'outside_lights_off_2' 
  triggers:
    - trigger: time
      at: '04:10:00'

  actions:
    - action: homeassistant.turn_off
      entity_id: light.garage
    - action: homeassistant.turn_off
      entity_id: light.landscape  

        ##########################################################
        ## Turn Off Front Door After Hours From Motion - No Landscape
        ##########################################################

#- alias: Front Door Lights Off After Motion

#  triggers:
#    - trigger: state
#      entity_id: light.front_door
#      to: 'on'
#      for:
#        minutes: 15

#  conditions:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
#    - condition: time
#      after: '23:35:00'
#      before: '04:00:00'

#  actions:
#    - action: light.turn_off
#      entity_id: light.front_door
#      data:
#        transition: 15

        ##########################################################
        ## Turn Off Front Door After Hours From Motion
        ##########################################################

#- alias: Front Lights Off After Motion

#  triggers:
#    - trigger: state
#      entity_id: light.front_door
#      to: 'on'
#      for:
#        minutes: 15

#  conditions:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
#    - condition: time
#      after: '04:01:00'
#      before: '08:00:00'

#  actions:
#    - action: light.turn_off
#      entity_id: light.front_door
#      data:
#        transition: 15
#    - action: light.turn_off
#      entity_id: light.landscape
#      data:
#        transition: 60


        ##########################################################
        ## Outside Lights - Landscape Hue Light Not On - Night
        ##########################################################

- alias: Outside Lights - Landscape Hue Light Fix - Night On
  id: 'outside_lights_landscape_hue_light_fix_night_on' 
  
  triggers:
    - trigger: state
      entity_id: light.landscape
      to: 'on'
      for:
        minutes: 2
  conditions:
    condition: and
    conditions:
      - condition: time
        after: '17:01:00'
        before: '03:00:00'       
      - condition: or
        conditions:
        - condition: state
          entity_id: light.outdoor_spot_1
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_2
          state: 'off'        
        - condition: state
          entity_id: light.outdoor_spot_3
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_4
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_5
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_6
          state: 'off'        
        - condition: state
          entity_id: light.outdoor_spot_7
          state: 'off'     
  actions:
    - action: light.turn_on
      entity_id: light.landscape    

        ##########################################################
        ## Outside Lights - Garage Hue Light Not On
        ##########################################################

- alias: Outside Lights - Garage Hue Light Fix
  id: 'outside_lights_garage_hue_light_fix' 
  triggers:
    - trigger: state
      entity_id: light.garage
      to: 'on'
      for:
        minutes: 2
  conditions:
    condition: or
    conditions:
      - condition: state
        entity_id: light.garage_1
        state: "off"
      - condition: state
        entity_id: light.garage_2
        state: "off"
      - condition: state
        entity_id: light.garage_3
        state: "off"
  actions:
    - action: light.turn_on
      entity_id: light.garage      


        ##########################################################
        ## Garage Back Door Light On
        ##########################################################

- alias: Outside Lights - Garage Back Door Light On
  id: 'outside_lights_garage_back_door_light_on'

  triggers:
    - trigger: state
      entity_id: binary_sensor.garage_back_door
      from: 'off'
      to: 'on'
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  actions:
  - action: light.turn_on
    entity_id: light.garage_back_door
  - delay: "00:15:00"                  
  - action: light.turn_off
    entity_id: light.garage_back_door