#################################################################
## Outside Lighting Automation
#################################################################

        ##########################################################
        ## Turn off Front and Walkout Lights at 11:30pm
        ##########################################################

- alias: Front and Walkout Lights Off

  trigger:
    - platform: time
      at: '23:30:00'

  action:
    - service: homeassistant.turn_off
      entity_id: light.walkout
    - service: homeassistant.turn_off
      entity_id: light.front_door

        ##########################################################
        ## Dim Landscape and Garage Lights at 11:35pm
        ##########################################################

- alias: Landscape Lights Dim

  trigger:
    - platform: time
      at: '23:35:00'

  action:
    - service: light.turn_on
      entity_id: light.landscape
      data:
        transition: 5
        brightness_pct: 50
    - service: light.turn_on
      entity_id: light.garage
      data:
        transition: 5
        brightness_pct: 50

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:00am
        ##########################################################

- alias: Outside Lights Off

  trigger:
    - platform: time
      at: '04:00:00'

  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
    - service: homeassistant.turn_off
      entity_id: light.landscape

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:10am
        ##########################################################

- alias: Outside Lights Off 2

  trigger:
    - platform: time
      at: '04:10:00'

  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
    - service: homeassistant.turn_off
      entity_id: light.landscape

        ##########################################################
        ## Turn Off Front Door After Hours From Motion - No Landscape
        ##########################################################

- alias: Front Door Lights Off After Motion

  trigger:
    - platform: state
      entity_id: light.front_door
      to: 'on'
      for:
        minutes: 15

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '23:35:00'
      before: '04:00:00'

  action:
    - service: light.turn_off
      entity_id: light.front_door
      data:
        transition: 15

        ##########################################################
        ## Turn Off Front Door After Hours From Motion
        ##########################################################

- alias: Front Lights Off After Motion

  trigger:
    - platform: state
      entity_id: light.front_door
      to: 'on'
      for:
        minutes: 15

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '04:01:00'
      before: '06:00:00'

  action:
    - service: light.turn_off
      entity_id: light.front_door
      data:
        transition: 15
    - service: light.turn_off
      entity_id: light.landscape
      data:
        transition: 60


        ##########################################################
        ## Landscape Hue Light Not On - Night
        ##########################################################

- alias: Landscape Hue Light Fix - Night On

  trigger:
    - platform: state
      entity_id: light.landscape
      to: 'on'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: time
        after: '17:01:00'
        before: '03:00:00'       
      - condition: or
        conditions:
        - condition: state
          entity_id: light.outdoor_spot_1
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_2
          state: 'off'        
        - condition: state
          entity_id: light.outdoor_spot_3
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_4
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_5
          state: 'off'
        - condition: state
          entity_id: light.outdoor_spot_6
          state: 'off'        
        - condition: state
          entity_id: light.outdoor_spot_7
          state: 'off'     
  action:
    - service: light.turn_on
      entity_id: light.landscape    

        ##########################################################
        ## Garage Hue Light Not On
        ##########################################################

- alias: Garage Hue Light Fix

  trigger:
    - platform: state
      entity_id: light.garage
      to: 'on'
      for:
        minutes: 2
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.garage_1
        state: "off"
      - condition: state
        entity_id: light.garage_2
        state: "off"
      - condition: state
        entity_id: light.garage_3
        state: "off"
  action:
    - service: light.turn_on
      entity_id: light.garage      
