##################################################################
## Party Mode Automations
##################################################################

        ##########################################################
        ## Outside Party Mode
        ##########################################################

- alias: Party - Outside to Colorloop

  triggers:
    - trigger: state
      entity_id: input_boolean.party_outside
      to: 'on'

  actions:
    - delay: "00:00:25"
    - action: light.turn_on
      entity_id: light.garage
      data:
        effect: colorloop
        transition: 5
        brightness_pct: 100


        ##########################################################
        ## Family Room Party Mode
        ##########################################################

- alias: Party - Set Family Room to Random Color
  id: party_family_room_color_on

  triggers:
    - trigger: time_pattern
      seconds: '/6'

  conditions:
    - condition: state
      entity_id: input_boolean.party_family_room
      state: 'on'

  actions:
    - action: light.turn_on
      entity_id: light.family_room
      data:
        transition: 5
        brightness_pct: 100
        color_name: "{{ ['lawngreen', 'blueviolet', 'magenta', 'yellow', 'red'] | random }}"

        ##########################################################
        ## Family Room Random Colors Off
        ##########################################################

- alias: Party - Set Family Room to Random Color Off

  triggers:
    - trigger: state
      entity_id: input_boolean.party_family_room
      to: 'off'

  actions:
    - action: light.turn_on
      entity_id:
        - light.family_room
      data:
        transition: 30
        brightness_pct: 100
        kelvin: 2700

        ##########################################################
        ## USER4 Bedroom Party Mode
        ##########################################################

- alias: Party - Set USER4 Bedroom to Random Color

  triggers:
    - trigger: state
      entity_id: input_boolean.party_USER4_bedroom
      to: 'on'

  actions:
    - action: light.turn_on
      entity_id: light.USER4_bedroom
      data:
        effect: colorloop
        transition: 5
        brightness_pct: 100

        ##########################################################
        ## USER4 Bedroom Random Colors Off
        ##########################################################

- alias: Party - Set USER4 Bedroom to Random Color Off

  triggers:
    - trigger: state
      entity_id: input_boolean.party_USER4_bedroom
      to: 'off'

  actions:
    - action: light.turn_on
      entity_id:
        - light.USER4_bedroom
      data:
        transition: 30
        brightness_pct: 100
        kelvin: 2700


        ##########################################################
        ## Test Party Mode
        ##########################################################

- alias: Party - Set Test Random Color

  triggers:
    - trigger: time_pattern
      seconds: '/6'

  conditions:
    - condition: state
      entity_id: input_boolean.party_family_room
      state: 'on'

  actions:
    - action: light.turn_on
      entity_id: light.family_room_2
      data:
        transition: 5
        brightness_pct: 100
        color_name: "{{ ['lawngreen', 'blueviolet', 'magenta', 'yellow', 'red'] | random }}"
