#################################################################
## Roomba - Notifications and Automations
#################################################################

        ##########################################################
        ## Roomba is Stuck Notification
        ##########################################################

- alias: Roomba - Stuck Notification

  trigger:
    - platform: template
      value_template: "{%if is_state_attr('vacuum.rosie', 'status', 'Stuck') %}true{%endif%}"

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: Rosie is Stuck, Please Help
    - service: notify.mobile_app_USER2_iphone
      data:
        message: Rosie is Stuck, Please Help

        ##########################################################
        ## Roomba is Full Notification
        ##########################################################

- alias: Roomba - Full Notification

  trigger:
    - platform: template
      value_template: "{%if is_state_attr('vacuum.rosie', 'bin_full', true) %}true{%endif%}"

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: Rosie is Full, Empty It
    - service: notify.mobile_app_USER2_iphone
      data:
        message: Rosie is Full, Empty It
