#################################################################
## Nest Protect Sensor Automations
#################################################################

        ##########################################################
        ## Flash Lights for Smoke - Warning
        ##########################################################
- alias: Smoke Sensor - Flash Lights when Smoke Warning

  trigger:
    - platform: state
      entity_id: sensor.hallway_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.master_bedroom_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "red"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long
    - service: notify.ios_USER1_iphone
      data:
        message: "Smoke - Warning in House!"
    - service: notify.ios_USER2_iphone
      data:
        message: "Smoke - Warning in House!"

        ##########################################################
        ## Flash Lights for Smoke - Emergency
        ##########################################################
- alias: Smoke Sensor - Flash Lights when Smoke Emergency

  trigger:
    - platform: state
      entity_id: sensor.hallway_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.master_bedroom_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "red"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long
    - service: notify.ios_USER1_iphone
      data:
        message: "Smoke - Emergency in House!"
    - service: notify.ios_USER2_iphone
      data:
        message: "Smoke - Emergency in House!"
        ##########################################################
        ## Flash Lights for CO - Warning
        ##########################################################
- alias: Smoke Sensor - Flash Lights when CO Warning

  trigger:
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_co_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.master_bedroom_nest_protect_co_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_co_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 3
  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "orange"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long
    - service: notify.ios_USER1_iphone
      data:
        message: "CO - Warning in House!"
    - service: notify.ios_USER2_iphone
      data:
        message: "CO - Warning in House!"

        ##########################################################
        ## Flash Lights for CO - Emergency
        ##########################################################

- alias: Smoke Sensor - Flash Lights when CO Emergency

  trigger:
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.master_bedroom_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "orange"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long
    - service: notify.ios_USER1_iphone
      data:
        message: "CO - Emergency in House!"
    - service: notify.ios_USER2_iphone
      data:
        message: "CO - Emergency in House!"
