##################################################################
## Sports Mode Automations
##################################################################

        ##########################################################
        ## Blackhawks Goal - On
        ##########################################################

- alias: Blackhawks Goal - On

  trigger:
    platform: state
    entity_id: input_boolean.blackhawks_goal
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.blackhawks_mode
      state: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.office
        media_content_id: https://REDACTED/local/audio/blackhawks_goal.mp3
        media_content_type: music
    - service: light.turn_on
      entity_id: light.family_room
      data:
        color_name: red
        brightness_pct: 100
    - service: light.turn_on
      entity_id: light.family_room
      data:
        flash: long
    - delay: "00:00:10"
    - service: light.turn_on
      entity_id: light.family_room
      data:
        flash: long
    - delay: "00:00:10"
    - service: light.turn_on
      entity_id: light.family_room
      data:
        flash: long

        ##########################################################
        ## Blackhawks Goal - Off
        ##########################################################

- alias: Blackhawks Goal - Off

  trigger:
    platform: state
    entity_id: input_boolean.blackhawks_goal
    to: 'on'
    for:
      seconds: 50
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.blackhawks_goal
  - service: light.turn_on
    entity_id: light.family_room
    data:
      color_name: white
      brightness_pct: 100
  - service: light.turn_on
    entity_id:
      - light.family_room
    data:
      transition: 10
      brightness_pct: 100
      kelvin: 2700

        ##########################################################
        ## Blackhawks Mode - Off
        ##########################################################

- alias: Blackhawks Mode - Off

  trigger:
    platform: state
    entity_id: input_boolean.blackhawks_mode
    to: 'on'
    for:
      hours: 4
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.blackhawks_mode

        ##########################################################
        ## Cardinals Score - On
        ##########################################################

- alias: Cardinals Score - On

  trigger:
    platform: state
    entity_id: input_boolean.cardinals_score
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.cardinals_mode
      state: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.office
        media_content_id: https://REDACTED/local/audio/cardinals_score.mp3
        media_content_type: music
    - service: light.turn_on
      entity_id: light.family_room
      data:
        color_name: red
        brightness_pct: 100
    - service: light.turn_on
      entity_id: light.family_room
      data:
        flash: long
    - delay: "00:00:10"
    - service: light.turn_on
      entity_id: light.family_room
      data:
        flash: long
    - delay: "00:00:10"
    - service: light.turn_on
      entity_id: light.family_room
      data:
        flash: long

        ##########################################################
        ## Sports Goal - Off
        ##########################################################

- alias: Cardinals Score - Off

  trigger:
    platform: state
    entity_id: input_boolean.cardinals_score
    to: 'on'
    for:
      seconds: 50
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.cardinals_score
  - service: light.turn_on
    entity_id: light.family_room
    data:
      color_name: white
      brightness_pct: 100
  - service: light.turn_on
    entity_id:
      - light.family_room
    data:
      transition: 10
      brightness_pct: 100
      kelvin: 2700

        ##########################################################
        ## Cardinals Mode - Off
        ##########################################################

- alias: Cardinals Mode - Off

  trigger:
    platform: state
    entity_id: input_boolean.cardinals_mode
    to: 'on'
    for:
      hours: 4
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.cardinals_mode


        ##########################################################
        ## Blackhawks Goal TEST
        ##########################################################

- alias: Blackhawks Goal TEST

  trigger:
    platform: state
    entity_id: input_boolean.blackhawks_goal
    from: 'off'
    to: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.basement
        media_content_id: https://REDACTED/local/audio/blackhawks_goal.mp3
        media_content_type: music