#################################################################
## Tesla Automations
#################################################################

        ##########################################################
        ## Teslamate Update - GPS
        ##########################################################

- alias: Teslamate - Update Tesla location as MQTT location updates
  id: teslamate_update_location
  initial_state: on
  triggers:
    - trigger: mqtt
      topic: teslamate/cars/1/latitude
    - trigger: mqtt
      topic: teslamate/cars/1/longitude
  actions:
    - action: device_tracker.see
      data_template:
        dev_id: tesla_location
        gps:
          [
            "{{ states.sensor.tesla_latitude.state }}",
            "{{ states.sensor.tesla_longitude.state }}"
          ]

        ##########################################################
        ## Tesla Not Plugged In After 8pm 
        ##########################################################
- alias: Tesla Not Plugged In After 9pm
  id: tesla_not_plugged_in

  triggers:
    - trigger: time
      at: '21:00:00'

  conditions:
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: device_tracker.tesla_location
      state: 'home'
    - condition: state
      entity_id: binary_sensor.tesla_plugged_in
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Tesla Not Plugged In"
