#################################################################
## Vacation Automations
#################################################################

        ##########################################################
        ## Vacation Mode Lights on at Sunset
        ##########################################################

- alias: Vacation - Lights On Sunset

  triggers:
    - trigger: sun
      event: 'sunset'
      offset: '-00:10:00'

  conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  actions:
    - action: light.turn_on
      entity_id: light.family_room
    - action: light.turn_on
      entity_id: light.master_bedroom

        ##########################################################
        ## Vacation Mode Lights Off at 11p
        ##########################################################

- alias: Vacation - Lights Off 11p

  triggers:
    - trigger: time
      at: '23:34'

  conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  actions:
    - action: light.turn_off
      entity_id: light.family_room
    - action: light.turn_off
      entity_id: light.master_bedroom
