#################################################################
## Wakeup - Light Automations
#################################################################

        ##########################################################
        ## Wakeup All Activation
        ##########################################################

- alias: Wakeup All Activation

  trigger:
    platform: state
    entity_id: input_boolean.all_wakeup
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.USER2_wakeup
  - service: homeassistant.turn_on
    entity_id: input_boolean.USER3_wakeup  
  - service: homeassistant.turn_on
    entity_id: input_boolean.USER4_wakeup
  - service: homeassistant.turn_off
    entity_id: input_boolean.all_wakeup



        ##########################################################
        ## USER2 Wakeup Alarm
        ##########################################################
- alias: Alarm - USER2 Wakeup Light

  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.USER2_wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.USER2_wakeup
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.family_room
    - service: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        color_name: red
        brightness_pct: 10
        transition: 60
    - delay: "00:01:00"        
    - service: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        color_name: orange
        brightness_pct: 70
        transition: 120
    - delay: "00:02:00"           
    - service: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        color_name: gold
        brightness_pct: 80
        transition: 120
    - delay: "00:02:30"         
    - service: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 30
    - delay: "00:03:00"        
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER2_wakeup

        ##########################################################
        ## USER3 Wakeup Alarm
        ##########################################################
- alias: Alarm - USER3 Wakeup Light

  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.USER3_wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.USER3_wakeup
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        color_name: red
        brightness_pct: 10
        transition: 60
    - delay: "00:01:00"     
    - service: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        color_name: orange
        brightness_pct: 70
        transition: 120
    - delay: "00:02:00"          
    - service: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        color_name: gold
        brightness_pct: 80
        transition: 120
    - delay: "00:02:00"          
    - service: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 60
    - delay: "00:03:00"
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER3_wakeup

       ##########################################################
        ## USER4 Wakeup Alarm
        ##########################################################
- alias: Alarm - USER4 Wakeup Light

  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.USER4_wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.USER4_wakeup
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        color_name: red
        brightness_pct: 10
        transition: 60
    - delay: "00:01:00"     
    - service: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        color_name: orange
        brightness_pct: 70
        transition: 120
    - delay: "00:02:00"          
    - service: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        color_name: gold
        brightness_pct: 80
        transition: 120
    - delay: "00:02:00"          
    - service: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 60
    - delay: "00:03:00"
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER4_wakeup
