#################################################################
## Wakeup - Light Automations
#################################################################

        ##########################################################
        ## Wakeup All Activation
        ##########################################################

- alias: Wakeup All Activation
  id: 'wakeup_all_activation'

  triggers:
    trigger: state
    entity_id: input_boolean.all_wakeup
    to: 'on'
  actions:
  - action: homeassistant.turn_on
    entity_id: input_boolean.USER2_wakeup
  - action: homeassistant.turn_on
    entity_id: input_boolean.USER3_wakeup  
  - action: homeassistant.turn_on
    entity_id: input_boolean.USER4_wakeup
  - action: homeassistant.turn_off
    entity_id: input_boolean.all_wakeup



        ##########################################################
        ## USER2 Wakeup Alarm
        ##########################################################
- alias: Alarm - USER2 Wakeup Light
  id: 'wakeup_USER2_wakeup_light'

  triggers:
    - trigger: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.USER2_wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  conditions:
    - condition: state
      entity_id: input_boolean.USER2_wakeup
      state: 'on'
  actions:
    - action: light.turn_on
      entity_id: light.family_room
    - action: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        color_name: red
        brightness_pct: 10
        transition: 60
    - delay: "00:01:00"        
    - action: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        color_name: orange
        brightness_pct: 70
        transition: 120
    - delay: "00:02:00"           
    - action: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        color_name: gold
        brightness_pct: 80
        transition: 120
    - delay: "00:02:30"         
    - action: light.turn_on
      entity_id: light.USER2_bedroom_1
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 30
    - delay: "00:03:00"        
    - action: homeassistant.turn_off
      entity_id: input_boolean.USER2_wakeup

        ##########################################################
        ## USER3 Wakeup Alarm
        ##########################################################
- alias: Alarm - USER3 Wakeup Light
  id: 'wakeup_USER3_wakeup_light'

  triggers:
    - trigger: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.USER3_wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  conditions:
    - condition: state
      entity_id: input_boolean.USER3_wakeup
      state: 'on'
  actions:
    - action: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        color_name: red
        brightness_pct: 10
        transition: 60
    - delay: "00:01:00"     
    - action: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        color_name: orange
        brightness_pct: 70
        transition: 120
    - delay: "00:02:00"          
    - action: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        color_name: gold
        brightness_pct: 80
        transition: 120
    - delay: "00:02:00"          
    - action: light.turn_on
      entity_id: light.USER3_bedroom_1
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 60
    - delay: "00:03:00"
    - action: homeassistant.turn_off
      entity_id: input_boolean.USER3_wakeup

       ##########################################################
        ## USER4 Wakeup Alarm
        ##########################################################
- alias: Alarm - USER4 Wakeup Light
  id: 'wakeup_USER4_wakeup_light'

  triggers:
    - trigger: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.USER4_wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  conditions:
    - condition: state
      entity_id: input_boolean.USER4_wakeup
      state: 'on'
  actions:
    - action: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        color_name: red
        brightness_pct: 10
        transition: 60
    - delay: "00:01:00"     
    - action: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        color_name: orange
        brightness_pct: 70
        transition: 120
    - delay: "00:02:00"          
    - action: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        color_name: gold
        brightness_pct: 80
        transition: 120
    - delay: "00:02:00"          
    - action: light.turn_on
      entity_id: light.USER4_bedroom_1
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 60
    - delay: "00:03:00"
    - action: homeassistant.turn_off
      entity_id: input_boolean.USER4_wakeup