#################################################################
## Water Treatment System Automations
#################################################################

        ##########################################################
        ## Lift Station Activations Counter
        ##########################################################

- alias: Lift Station Activations Counter

  trigger:
    - platform: state
      entity_id: sensor.lift_station_status
      from: 'not running'
      to: 'running'
      
  action:  
    - service: counter.increment
      entity_id: counter.lift_station_activations_counter
    - service: counter.increment
      entity_id: counter.lift_station_activations_counter_current_day
      
        ##########################################################
        ## Lift Station Activations Counter - Daily
        ##########################################################

- alias: Lift Station Activations Counter - Daily
  trigger:
    - platform: time
      at: '23:59'

  action:
    - service: counter.configure
      data_template:
        entity_id: counter.lift_station_activations_counter_last_day
        value: "{{ states.counter.lift_station_activations_counter_current_day.state | int }}" 
    - service: counter.reset
      entity_id: counter.lift_station_activations_counter_current_day
