#################################################################
## Water Sensor Automations
#################################################################

        ##########################################################
        ## Send Notification for Water Detected Basement
        ##########################################################

- alias: Notification - Basement Water Sensor

  triggers:
    - trigger: state
      entity_id: binary_sensor.basement_drain_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected at Basement Drain!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0


    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Water Detected at Basement Drain!"

        ##########################################################
        ## Send Notification for Water Detected Washing Machine
        ##########################################################

- alias: Notification - Washing Machine Water Sensor Text Notification

  triggers:
    - trigger: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected at Washing Machine!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Water Detected by Washing Machine!"

        ##########################################################
        ## Send Notification for Water Detected Kitchen Sink
        ##########################################################

- alias: Notification - Kitchen Sink Water Sensor Text Notification

  triggers:
    - trigger: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected by Kitchen Sink!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Water Detected by Kitchen Sink!"


        ##########################################################
        ## Send Notification for Water Detected Refrigerator
        ##########################################################

- alias: Notification - Refrigerator Water Sensor

  triggers:
    - trigger: state
      entity_id: binary_sensor.refrigerator_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected under Refrigerator!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
    - action: notify.mobile_app_USER2_iphone
      data:
        message: "Water Detected by Refrigerator!"

        ##########################################################
        ## Turn off Washing Machine when Water Detected Washing Machine
        ##########################################################

- alias: Water Sensor - Washing Machine Shut Off

  triggers:
    - trigger: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  actions:
    - action: switch.turn_off
      entity_id:
        - switch.washing_machine

        ##########################################################
        ## Send Notification for Water Detected Filtration System
        ##########################################################

- alias: Notification - Filtration Water Sensor

  triggers:
    - trigger: state
      entity_id: binary_sensor.filtration_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected by Water Filtration in Basement!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
 #   - action: notify.mobile_app_USER2_iphone
 #     data:
 #       message: "Water Detected by Water Filtration!"

        ##########################################################
        ## Send Notification for Water Detected Red Sea Floor Sensor
        ##########################################################

- alias: Notification - Red Sea Floor Water Sensor

  triggers:
    - trigger: state
      entity_id: binary_sensor.red_sea_floor_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected on floor by Red Sea Tank in Basement!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
 #   - action: notify.mobile_app_USER2_iphone
 #     data:
 #       message: "Water Detected on floor by Red Sea Tank in Basement!"

        ##########################################################
        ## Send Notification for Water Detected Red Sea Sump Sensor
        ##########################################################

- alias: Notification - Red Sea Sump Water Sensor

  triggers:
    - trigger: state
      entity_id: binary_sensor.red_sea_sump_water_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  actions:
    - action: notify.mobile_app_USER1_iphone
      data:
       title: "Water Alert"
       message: "Water Detected in sump of Red Sea Tank in Basement!"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
 #   - action: notify.mobile_app_USER2_iphone
 #     data:
 #       message: "Water Detected on floor by Red Sea Tank in Basement!"

        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Sensor - Flash Lights when Water Detected

  triggers:
    - trigger: state
      entity_id: binary_sensor.basement_drain_water_sensor
      from: 'off'
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      from: 'off'
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.refridgerator_water_sensor
      from: 'off'
      to: 'on'
#    - trigger: state
#      entity_id: binary_sensor.filtration_water_sensor
#      from: 'off'
#      to: 'on'     
  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  actions:
    - action: light.turn_on
      entity_id: light.water_lights
      data:
        brightness_pct: 100
        color_name: "blue"
    - action: light.turn_on
      entity_id: light.water_lights
      data:
        flash: long
    - delay: "00:00:10"
    - action: light.turn_on
      entity_id: light.water_lights
      data:
        flash: long
    - delay: "00:00:10"
    - action: light.turn_on
      entity_id: light.water_lights
      data:
        brightness_pct: 100
        kelvin: 2700


##########################################################
## TEST REPEAR - Flash Lights when Water Detected
##########################################################

- alias: Repeat Test Water Sensor - Flash Lights when Water Detected

  triggers:
    - trigger: state
      entity_id: binary_sensor.pantry_door
      from: 'off'
      to: 'on'     
  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  mode: single
  actions:
    - alias: repeat flash until water not detected
      repeat:
        sequence:
          # Run command that for some reason doesn't always work
          - action: light.turn_on
            entity_id: light.family_room_1
            data:
              brightness_pct: 100
              color_name: "blue"
          - action: light.turn_on
            entity_id: light.family_room_1
            data:
              flash: long
          - delay: '00:00:10'    
        until:
          - condition: state
            entity_id: binary_sensor.pantry_door
            state: 'off'


