#################################################################
## Water Treatment System Automations
#################################################################

        ##########################################################
        ## Lift Station Activations Counter and Notification
        ##########################################################

- alias: Lift Station Activations Counter

  triggers:
    - trigger: state
      entity_id: sensor.lift_station_status
      to: 'running'
      
  action:  
    - action: counter.increment
      entity_id: counter.lift_station_activations_counter
    - action: counter.increment
      entity_id: counter.lift_station_activations_counter_current_day
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Lift Station Running - {{states.counter.lift_station_activations_counter_current_day.state}}"
      
        ##########################################################
        ## Lift Station Activations Counter - Daily
        ##########################################################

- alias: Lift Station Activations Counter - Daily
  triggers:
    - trigger: time
      at: '23:59:00'

  actions:
    - action: counter.set_value
      data_template:
        entity_id: counter.lift_station_activations_counter_last_day
        value: "{{ states.counter.lift_station_activations_counter_current_day.state | int }}" 
    - action: counter.reset
      entity_id: counter.lift_station_activations_counter_current_day

        ##########################################################
        ## Lift Station Check System Notification
        ##########################################################

- alias: Lift Station Check System

  triggers:
    - trigger: state
      entity_id: sensor.lift_station_status
      to: 'check system'
      for:
        hours: 0
        minutes: 3
        seconds: 0
      
  action:  
    - action: notify.mobile_app_USER1_iphone
      data:
        message: "Lift Station Error - Check Status - {{states.sensor.esp_energy_ct1_lift_station_watts.state}}"