#################################################################
## Weather Alerts and Automations
#################################################################

        ##########################################################
        ## Winter Weather Warning
        ##########################################################

- alias: Weather - Winter Weather Warning

  trigger:
    - platform: state
      entity_id: sensor.nws_winter_storm_warning
      from: "0"
      to: "1"

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
       message: "NWS -- {{ states.sensor.nws_warnings.attributes.winter_storm_warning_headline }}"

        ##########################################################
        ## Tornado Warning
        ##########################################################

- alias: Weather - Tornado Warning

  trigger:
    - platform: state
      entity_id: sensor.nws_tornado_warning
      from: "0"
      to: "1"

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
       title: "Tornado Warning"
       message: "NWS -- {{ states.sensor.nws_warnings.attributes.tornado_warning_headline }}"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0
    - service: notify.mobile_app_USER2_iphone
      data:
       title: "Tornado Warning"
       message: "NWS -- {{ states.sensor.nws_warnings.attributes.tornado_warning_headline }}"
       data:
         push:
           sound:
             name: default
             critical: 1
             volume: 1.0

        ##########################################################
        ## Tornado Watch
        ##########################################################

- alias: Weather - Tornado Watch

  trigger:
    - platform: state
      entity_id: sensor.nws_tornado_watch
      from: "0"
      to: "1"

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
       message: "NWS -- {{ states.sensor.nws_warnings.attributes.tornado_watch_headline }}"