##################################################################
## Basement Default Mode
##################################################################

        ##########################################################
        ## Default Mode
        ##########################################################

- alias: Basement Theme - Default On

  triggers:
    - trigger: state
      entity_id: input_select.basement_theme
      to:  'Default'

  actions:
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        transition: 5
        brightness_pct: 100
        effect: "Warm White"
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        transition: 5
        brightness_pct: 100
        effect: "Warm White"