##################################################################
## Basement Party Mode
##################################################################

        ##########################################################
        ## Party Mode
        ##########################################################

- alias: Basement Theme - Party Mode On

  triggers:
    - trigger: state
      entity_id: input_select.basement_theme
      to: 'Party'

  actions:
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        transition: 10
        effect: "Party"
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        transition: 10
        effect: "Party"