##################################################################
## Basement TV Mode
##################################################################

        ##########################################################
        ## TV Mode
        ##########################################################

- alias: Basement Theme - TV Mode On

  triggers:
    - trigger: state
      entity_id: input_select.basement_theme
      to: 'TV Mode'

  actions:
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        transition: 10
        effect: "TV time"
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        transition: 10
        effect: "TV time"
    - action: light.turn_off
      entity_id: light.basement_recessed_2
      data:
        transition: 10
    - action: light.turn_off
      entity_id: light.basement_recessed_5
      data:
        transition: 10