##################################################################
## Basement Red Alert Mode
##################################################################

        ##########################################################
        ## Red Alert Mode
        ##########################################################

- alias: Basement Theme - Red Alert

  triggers:
    - trigger: state
      entity_id: input_select.basement_theme
      to:  'Red Alert'

  actions:
    - delay: "00:00:10"     
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:02"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red
#    - delay: "00:00:05"
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:05"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red   
#    - delay: "00:00:05"
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:05"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red   
#    - delay: "00:00:05"
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:05"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red  
#    - delay: "00:00:05"
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:05"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red   
#    - delay: "00:00:05"
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:05"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red   
#    - delay: "00:00:05"
    - action: light.turn_off
      entity_id: light.basement_sitting_area
    - action: light.turn_off
      entity_id: light.basement_entry
#    - delay: "00:00:05"
    - action: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        brightness_pct: 100
        color_name: red
    - action: light.turn_on
      entity_id: light.basement_entry
      data:
        brightness_pct: 100
        color_name: red           