##################################################################
## Basement None Mode
##################################################################

        ##########################################################
        ## None Mode
        ##########################################################

- alias: Basement Theme - None Reset

  triggers:
    - trigger: state
      entity_id: light.basement
      to:  'off'

  actions:
    - action: input_select.select_option
      data:
        entity_id: input_select.basement_theme
        option: None